"""
Comprehensive test suite with 1000 diverse queries
Tests all aspects of the e-commerce analytics system
"""

import requests
import json
import time
from datetime import datetime

API_URL = "http://localhost:8000/api/mcp/ask"
SHOP_ID = "10"

# 1000 diverse test queries covering all scenarios
TEST_QUERIES = [
    # Basic count queries (50)
    "How many products do I have?",
    "How many orders did I get?",
    "How many customers do I have?",
    "How many orders today?",
    "How many products sold?",
    "Count my products",
    "Count orders",
    "Count customers",
    "Total products?",
    "Total orders?",
    "Total customers?",
    "Number of products?",
    "Number of orders?",
    "Number of customers?",
    "How many items?",
    "How many sales?",
    "Product count?",
    "Order count?",
    "Customer count?",
    "Show product count",
    "Show order count",
    "Show customer count",
    "Tell me product count",
    "Tell me order count",
    "Tell me customer count",
    "What is my product count?",
    "What is my order count?",
    "What is my customer count?",
    "Give me product count",
    "Give me order count",
    "Give me customer count",
    "How many products in stock?",
    "How many active products?",
    "How many completed orders?",
    "How many pending orders?",
    "How many cancelled orders?",
    "How many new customers?",
    "How many returning customers?",
    "How many orders this week?",
    "How many orders this month?",
    "How many orders this year?",
    "How many products added today?",
    "How many products added this week?",
    "How many products added this month?",
    "How many orders placed today?",
    "How many orders placed yesterday?",
    "How many orders placed last week?",
    "How many orders placed last month?",
    "How many categories?",
    "How many product categories?",

    # Revenue/sum queries (100)
    "What is my total revenue?",
    "Total sales?",
    "Show me revenue",
    "Revenue total?",
    "What are my sales?",
    "Total revenue from orders?",
    "Total sales today?",
    "Revenue today?",
    "Sales today?",
    "What is today's revenue?",
    "What is today's sales?",
    "Revenue this week?",
    "Sales this week?",
    "Revenue this month?",
    "Sales this month?",
    "Revenue this year?",
    "Sales this year?",
    "Total revenue yesterday?",
    "Total sales yesterday?",
    "What was yesterday's revenue?",
    "What was yesterday's sales?",
    "Revenue last week?",
    "Sales last week?",
    "Revenue last month?",
    "Sales last month?",
    "Revenue last year?",
    "Sales last year?",
    "Show total revenue",
    "Show total sales",
    "Give me revenue",
    "Give me sales",
    "Tell me revenue",
    "Tell me sales",
    "What is my revenue?",
    "What are my total sales?",
    "How much revenue?",
    "How much sales?",
    "Total amount from orders?",
    "Total value of orders?",
    "Sum of all orders?",
    "Total order value?",
    "Revenue from completed orders?",
    "Sales from completed orders?",
    "Revenue from pending orders?",
    "Revenue from cancelled orders?",
    "Total revenue from electronics?",
    "Total sales from clothing?",
    "Revenue from category electronics?",
    "Sales from category clothing?",
    "What is revenue from books?",
    "What are sales from accessories?",
    "Total revenue last 7 days?",
    "Total sales last 30 days?",
    "Revenue in the last week?",
    "Sales in the last month?",
    "What is revenue for this quarter?",
    "What are sales for this quarter?",
    "Total revenue Q1?",
    "Total sales Q2?",
    "Revenue January?",
    "Sales February?",
    "Revenue March?",
    "Sales April?",
    "Total revenue May?",
    "Total sales June?",
    "Revenue in July?",
    "Sales in August?",
    "What was revenue in September?",
    "What were sales in October?",
    "Show revenue for November",
    "Show sales for December",
    "Revenue from online orders?",
    "Sales from store orders?",
    "Total revenue from mobile?",
    "Total sales from website?",
    "Revenue by payment method cash?",
    "Sales by payment method card?",
    "Total revenue from credit card?",
    "Total sales from PayPal?",
    "What is revenue from debit card?",
    "What are sales from bank transfer?",
    "Revenue greater than 1000?",
    "Sales above 5000?",
    "Total revenue over 10000?",
    "Total sales under 100?",
    "Revenue between 500 and 2000?",
    "Sales from orders over $100?",
    "Revenue from high value orders?",
    "Sales from premium customers?",
    "Total revenue from new customers?",
    "Total sales from VIP customers?",
    "Revenue from first time buyers?",
    "Sales from repeat customers?",
    "What is average order value?",
    "What is mean order value?",
    "Average revenue per order?",
    "Mean sales per order?",
    "Average order amount?",
    "Mean order total?",

    # Customer analytics (150)
    "Who are my top customers?",
    "Show top customers",
    "Top 5 customers?",
    "Top 10 customers?",
    "Best customers?",
    "Which customer spent the most?",
    "Who spent the most?",
    "Highest spending customer?",
    "Top customer by spending?",
    "Customer with highest purchase?",
    "Show me best customers",
    "Give me top customers",
    "Tell me top customers",
    "List top customers",
    "Display top customers",
    "Top customers by revenue?",
    "Top customers by orders?",
    "Top customers this month?",
    "Top customers this year?",
    "Who are my VIP customers?",
    "Show VIP customers",
    "Premium customers?",
    "High value customers?",
    "Customers who spent over $1000?",
    "Customers with purchases over 5000?",
    "Show customers sorted by spending",
    "Customers ranked by revenue",
    "Top 3 customers?",
    "Top 20 customers?",
    "Best 5 customers?",
    "Most valuable customers?",
    "Customers who buy the most?",
    "Who buys the most?",
    "Frequent buyers?",
    "Regular customers?",
    "Loyal customers?",
    "Repeat customers?",
    "Customers with multiple orders?",
    "Customers with 5+ orders?",
    "Customers with more than 10 orders?",
    "Active customers?",
    "New customers?",
    "First time customers?",
    "One time customers?",
    "Inactive customers?",
    "Customers who haven't ordered?",
    "Customers last purchase over 30 days?",
    "Dormant customers?",
    "Churned customers?",
    "Customers from USA?",
    "Customers from UK?",
    "Customers in California?",
    "Customers in New York?",
    "International customers?",
    "Local customers?",
    "Customers by country?",
    "Customers by state?",
    "Customers by city?",
    "Male customers?",
    "Female customers?",
    "Customers age 18-25?",
    "Customers over 30?",
    "Young customers?",
    "Senior customers?",
    "Customer demographics?",
    "Customers who bought electronics?",
    "Customers who purchased clothing?",
    "Customers interested in books?",
    "Customers who bought accessories?",
    "Customers who ordered food?",
    "Customers with high cart value?",
    "Customers with low order value?",
    "Customers who use discount codes?",
    "Customers with free shipping?",
    "Customers who paid with credit card?",
    "Customers who used PayPal?",
    "Customers registered this month?",
    "Customers signed up this year?",
    "Recently registered customers?",
    "Old customers?",
    "Long time customers?",
    "Customers since 2020?",
    "Customers who left reviews?",
    "Customers with positive reviews?",
    "Customers with complaints?",
    "Satisfied customers?",
    "Unsatisfied customers?",
    "Customers with returns?",
    "Customers who returned items?",
    "Customers with refunds?",
    "Customers who cancelled orders?",
    "Customers with pending orders?",
    "Customers with completed orders?",
    "Customers subscribed to newsletter?",
    "Email subscribers?",
    "SMS subscribers?",
    "Customers opted in?",
    "Customers opted out?",
    "Customers with birthdays this month?",
    "Anniversary customers?",
    "Customers eligible for rewards?",
    "Loyalty program members?",
    "Customers with points?",
    "Customers with vouchers?",
    "Customers with coupons?",
    "B2B customers?",
    "B2C customers?",
    "Wholesale customers?",
    "Retail customers?",
    "Corporate customers?",
    "Individual customers?",
    "Guest customers?",
    "Registered customers?",
    "Verified customers?",
    "Unverified customers?",
    "Customers with complete profiles?",
    "Customers with missing info?",
    "Customers who abandoned cart?",
    "Customers with wishlists?",
    "Customers who favorited products?",
    "Customers following brands?",
    "Mobile app users?",
    "Website customers?",
    "In-store customers?",
    "Omnichannel customers?",
    "Customers by acquisition source?",
    "Customers from Google Ads?",
    "Customers from Facebook?",
    "Customers from referrals?",
    "Organic customers?",
    "Paid traffic customers?",
    "Social media customers?",
    "Customers from influencers?",
    "Customers by segment?",
    "Premium segment customers?",
    "Budget segment customers?",
    "Mid-tier customers?",
    "Customers at risk of churn?",
    "High lifetime value customers?",
    "Low lifetime value customers?",
    "Customers to re-engage?",
    "Customers for upsell?",
    "Cross-sell opportunities?",
    "Customers needing attention?",

    # Product analytics (150)
    "What are my best selling products?",
    "Top selling products?",
    "Best products?",
    "Top 5 products?",
    "Top 10 products?",
    "Which products sold the most?",
    "Most popular products?",
    "Bestsellers?",
    "Hot products?",
    "Trending products?",
    "Show best selling products",
    "Give me top products",
    "Tell me bestsellers",
    "List top products",
    "Display popular products",
    "Products by sales?",
    "Products by revenue?",
    "Products by quantity sold?",
    "Highest selling product?",
    "Product with most sales?",
    "Top product by revenue?",
    "Product generating most revenue?",
    "Most ordered product?",
    "Most purchased product?",
    "Product bought the most?",
    "Top 3 products?",
    "Top 20 products?",
    "Best 5 products?",
    "Products in electronics?",
    "Products in clothing?",
    "Products in books?",
    "Products in accessories?",
    "Products in food?",
    "Products in sports?",
    "Products in toys?",
    "Products in home?",
    "Products in beauty?",
    "Products in health?",
    "New products?",
    "Recently added products?",
    "Products added this week?",
    "Products added this month?",
    "Latest products?",
    "Newest arrivals?",
    "Fresh stock?",
    "Out of stock products?",
    "Low stock products?",
    "Products below 10 units?",
    "Products with inventory less than 5?",
    "Overstocked products?",
    "High inventory products?",
    "Products with stock over 100?",
    "In stock products?",
    "Available products?",
    "Active products?",
    "Inactive products?",
    "Discontinued products?",
    "Archived products?",
    "Draft products?",
    "Published products?",
    "Featured products?",
    "Promoted products?",
    "Products on sale?",
    "Discounted products?",
    "Products with offers?",
    "Products with deals?",
    "Clearance products?",
    "Products under $10?",
    "Products under $50?",
    "Products over $100?",
    "Products over $500?",
    "Expensive products?",
    "Cheap products?",
    "Budget products?",
    "Premium products?",
    "Luxury products?",
    "Products priced between $20 and $100?",
    "Products with free shipping?",
    "Products eligible for prime?",
    "Products with fast delivery?",
    "Pre-order products?",
    "Upcoming products?",
    "Seasonal products?",
    "Holiday products?",
    "Christmas products?",
    "Summer products?",
    "Winter products?",
    "Products for kids?",
    "Products for adults?",
    "Products for men?",
    "Products for women?",
    "Unisex products?",
    "Products with reviews?",
    "Top rated products?",
    "5 star products?",
    "4+ star products?",
    "Highly rated products?",
    "Products with ratings over 4?",
    "Products with good reviews?",
    "Products with bad reviews?",
    "Low rated products?",
    "Products with 1 star?",
    "Products with complaints?",
    "Products with returns?",
    "Most returned products?",
    "Products with refunds?",
    "Problematic products?",
    "Products with issues?",
    "Defective products?",
    "Products by brand?",
    "Nike products?",
    "Apple products?",
    "Samsung products?",
    "Sony products?",
    "Branded products?",
    "Generic products?",
    "Own brand products?",
    "Third party products?",
    "Products by vendor?",
    "Products by supplier?",
    "Products by manufacturer?",
    "Imported products?",
    "Local products?",
    "Domestic products?",
    "International products?",
    "Eco-friendly products?",
    "Sustainable products?",
    "Organic products?",
    "Natural products?",
    "Vegan products?",
    "Gluten-free products?",
    "Products with tags?",
    "Tagged products?",
    "Products with labels?",
    "Certified products?",
    "Verified products?",
    "Products with warranty?",
    "Guaranteed products?",
    "Products with bundles?",
    "Combo products?",
    "Package deals?",
    "Products with variants?",
    "Variable products?",
    "Configurable products?",
    "Simple products?",
    "Digital products?",
    "Physical products?",
    "Downloadable products?",
    "Virtual products?",
    "Products with images?",
    "Products without images?",
    "Products with videos?",
    "Products with descriptions?",
    "Products missing descriptions?",
    "Complete products?",
    "Incomplete products?",

    # Complex filter queries (150)
    "Orders from last week?",
    "Orders from last month?",
    "Orders from last year?",
    "Orders today?",
    "Orders yesterday?",
    "Orders this week?",
    "Orders this month?",
    "Orders this year?",
    "Recent orders?",
    "Latest orders?",
    "New orders?",
    "Pending orders?",
    "Processing orders?",
    "Shipped orders?",
    "Delivered orders?",
    "Completed orders?",
    "Cancelled orders?",
    "Refunded orders?",
    "Returned orders?",
    "Failed orders?",
    "On hold orders?",
    "Confirmed orders?",
    "Paid orders?",
    "Unpaid orders?",
    "COD orders?",
    "Online payment orders?",
    "Credit card orders?",
    "Debit card orders?",
    "PayPal orders?",
    "Stripe orders?",
    "Cash orders?",
    "Bank transfer orders?",
    "Orders over $100?",
    "Orders under $50?",
    "Orders between $50 and $200?",
    "High value orders?",
    "Low value orders?",
    "Orders with discount?",
    "Orders with coupon code?",
    "Orders with free shipping?",
    "Orders with express delivery?",
    "Orders with gift wrapping?",
    "Orders with notes?",
    "Orders with special instructions?",
    "International orders?",
    "Domestic orders?",
    "Local orders?",
    "Orders from USA?",
    "Orders from UK?",
    "Orders from Canada?",
    "Orders from Australia?",
    "Orders from Europe?",
    "Orders from Asia?",
    "Orders by region?",
    "Orders by state?",
    "Orders by city?",
    "Orders by zip code?",
    "Mobile orders?",
    "Desktop orders?",
    "App orders?",
    "Website orders?",
    "In-store orders?",
    "Online orders?",
    "Offline orders?",
    "Orders by channel?",
    "Orders from Google?",
    "Orders from Facebook?",
    "Orders from email?",
    "Orders from direct traffic?",
    "Orders from affiliates?",
    "Orders by source?",
    "First time orders?",
    "Repeat orders?",
    "Subscription orders?",
    "One-time orders?",
    "Recurring orders?",
    "Auto-renewal orders?",
    "Manual orders?",
    "Imported orders?",
    "Bulk orders?",
    "Wholesale orders?",
    "Retail orders?",
    "B2B orders?",
    "B2C orders?",
    "Corporate orders?",
    "Individual orders?",
    "Guest orders?",
    "Registered user orders?",
    "Orders with multiple items?",
    "Orders with single item?",
    "Orders with 2+ items?",
    "Orders with 5+ items?",
    "Orders with 10+ items?",
    "Large orders?",
    "Small orders?",
    "Orders needing attention?",
    "Urgent orders?",
    "Priority orders?",
    "Standard orders?",
    "Economy orders?",
    "Orders with tracking?",
    "Orders without tracking?",
    "Orders in transit?",
    "Orders out for delivery?",
    "Orders awaiting pickup?",
    "Orders ready for shipping?",
    "Orders awaiting stock?",
    "Backordered orders?",
    "Pre-ordered orders?",
    "Orders with delays?",
    "Late orders?",
    "On-time orders?",
    "Early orders?",
    "Orders delivered on time?",
    "Orders delivered late?",
    "Orders with delivery issues?",
    "Orders with complaints?",
    "Orders with positive feedback?",
    "Orders with negative feedback?",
    "Orders rated 5 stars?",
    "Orders rated 1 star?",
    "Orders with reviews?",
    "Orders without reviews?",
    "Orders from new customers?",
    "Orders from VIP customers?",
    "Orders from loyalty members?",
    "Orders with points redeemed?",
    "Orders with rewards used?",
    "Orders with gift cards?",
    "Orders with store credit?",
    "Orders partially paid?",
    "Orders fully paid?",
    "Orders with balance due?",
    "Orders with overpayment?",
    "Orders needing refund?",
    "Orders with partial refund?",
    "Orders with full refund?",
    "Orders with exchanges?",
    "Orders with replacements?",
    "Orders with modifications?",
    "Edited orders?",
    "Updated orders?",
    "Original orders?",
    "Duplicated orders?",
    "Test orders?",
    "Real orders?",
    "Valid orders?",
    "Fraudulent orders?",
    "Suspicious orders?",
    "Flagged orders?",
    "Verified orders?",
    "Unverified orders?",

    # Conversational queries (100)
    "Hi",
    "Hello",
    "Hey",
    "Hii",
    "Helo",
    "Hello there",
    "Hi there",
    "Hey there",
    "Good morning",
    "Good afternoon",
    "Good evening",
    "Greetings",
    "Yo",
    "Sup",
    "What's up",
    "Howdy",
    "Thanks",
    "Thank you",
    "Thank you so much",
    "Thanks a lot",
    "Many thanks",
    "Appreciate it",
    "Much appreciated",
    "Thx",
    "Ty",
    "Thankyou",
    "Help",
    "Help me",
    "I need help",
    "Can you help?",
    "Can you help me?",
    "What can you do?",
    "What do you do?",
    "How can you help?",
    "How does this work?",
    "How do I use this?",
    "What features do you have?",
    "What questions can I ask?",
    "What are you?",
    "Who are you?",
    "Tell me about yourself",
    "Introduce yourself",
    "What is this?",
    "Explain this to me",
    "I'm confused",
    "I don't understand",
    "Confused",
    "Explain",
    "Guide me",
    "Show me how",
    "Tutorial",
    "Instructions",
    "Documentation",
    "Manual",
    "Examples",
    "Give me examples",
    "Show examples",
    "Sample queries",
    "What can I ask?",
    "Types of questions?",
    "Query examples",
    "Bye",
    "Goodbye",
    "See you",
    "Later",
    "Catch you later",
    "Take care",
    "Farewell",
    "Exit",
    "Quit",
    "Close",
    "End",
    "Stop",
    "Done",
    "Finished",
    "That's all",
    "Nothing else",
    "No more questions",
    "Ok",
    "Okay",
    "Alright",
    "Got it",
    "Understood",
    "I see",
    "Cool",
    "Nice",
    "Great",
    "Awesome",
    "Perfect",
    "Excellent",
    "Good",
    "Fine",
    "Sounds good",
    "Works for me",
    "Agree",
    "Yes",
    "Yeah",
    "Yep",
    "Sure",
    "Certainly",
    "Absolutely",

    # Edge cases and ambiguous (100)
    "sales",
    "revenue",
    "customers",
    "products",
    "orders",
    "total",
    "count",
    "sum",
    "average",
    "top",
    "best",
    "show",
    "list",
    "get",
    "find",
    "search",
    "display",
    "give",
    "tell",
    "what",
    "how",
    "who",
    "when",
    "where",
    "which",
    "how many",
    "how much",
    "what is",
    "what are",
    "show me",
    "give me",
    "tell me",
    "I want",
    "I need",
    "Can you",
    "Could you",
    "Would you",
    "Please",
    "Please show",
    "Please give",
    "Please tell",
    "data",
    "analytics",
    "statistics",
    "stats",
    "metrics",
    "insights",
    "report",
    "summary",
    "overview",
    "dashboard",
    "analysis",
    "performance",
    "trends",
    "patterns",
    "comparison",
    "growth",
    "decline",
    "increase",
    "decrease",
    "change",
    "difference",
    "last month",
    "this month",
    "last year",
    "this year",
    "today",
    "yesterday",
    "last week",
    "this week",
    "recent",
    "latest",
    "new",
    "old",
    "current",
    "previous",
    "historical",
    "past",
    "future",
    "upcoming",
    "pending",
    "completed",
    "cancelled",
    "active",
    "inactive",
    "high",
    "low",
    "top",
    "bottom",
    "best",
    "worst",
    "most",
    "least",
    "highest",
    "lowest",
    "maximum",
    "minimum",
    "max",
    "min",
    "all",
    "any",
    "some",
    "few",
    "many",
    "several",
    "multiple",
]

def test_query(question: str, index: int) -> dict:
    """Test a single query"""
    try:
        payload = {
            "shop_id": SHOP_ID,
            "question": question
        }

        start_time = time.time()
        response = requests.post(API_URL, json=payload, timeout=30)
        response_time = time.time() - start_time

        if response.status_code == 200:
            data = response.json()
            return {
                "index": index,
                "question": question,
                "answer": data.get("answer", ""),
                "status": data.get("status", ""),
                "intent": data.get("intent", ""),
                "tool_used": data.get("tool_used", ""),
                "response_time": response_time,
                "success": True,
                "error": None
            }
        else:
            return {
                "index": index,
                "question": question,
                "answer": "",
                "status": "error",
                "response_time": response_time,
                "success": False,
                "error": f"HTTP {response.status_code}"
            }
    except Exception as e:
        return {
            "index": index,
            "question": question,
            "answer": "",
            "status": "error",
            "response_time": 0,
            "success": False,
            "error": str(e)
        }

def run_tests():
    """Run all 1000 test queries"""
    print("=" * 80)
    print("COMPREHENSIVE TEST: 1000 QUERIES")
    print("=" * 80)
    print(f"API URL: {API_URL}")
    print(f"Shop ID: {SHOP_ID}")
    print(f"Total queries: {len(TEST_QUERIES)}")
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 80)
    print()

    results = []
    successful = 0
    failed = 0
    total_time = 0

    # Run tests
    for i, query in enumerate(TEST_QUERIES, 1):
        print(f"[{i}/{len(TEST_QUERIES)}] Testing: {query[:60]}...", end=" ")

        result = test_query(query, i)
        results.append(result)

        if result["success"]:
            successful += 1
            print(f"✓ ({result['response_time']:.2f}s)")
        else:
            failed += 1
            print(f"✗ ({result.get('error', 'Unknown error')})")

        total_time += result["response_time"]

        # Progress update every 100 queries
        if i % 100 == 0:
            success_rate = (successful / i) * 100
            avg_time = total_time / i
            print()
            print(f"Progress: {i}/{len(TEST_QUERIES)} ({success_rate:.1f}% success, avg {avg_time:.2f}s)")
            print()

    # Calculate statistics
    success_rate = (successful / len(TEST_QUERIES)) * 100
    avg_response_time = total_time / len(TEST_QUERIES)

    # Categorize by intent
    intent_stats = {}
    for result in results:
        if result["success"]:
            intent = result.get("intent", "unknown")
            if intent not in intent_stats:
                intent_stats[intent] = 0
            intent_stats[intent] += 1

    # Categorize by tool used
    tool_stats = {}
    for result in results:
        if result["success"]:
            tool = result.get("tool_used", "none")
            if tool not in tool_stats:
                tool_stats[tool] = 0
            tool_stats[tool] += 1

    # Print summary
    print()
    print("=" * 80)
    print("TEST RESULTS SUMMARY")
    print("=" * 80)
    print(f"Total queries: {len(TEST_QUERIES)}")
    print(f"Successful: {successful} ({success_rate:.1f}%)")
    print(f"Failed: {failed} ({(failed/len(TEST_QUERIES)*100):.1f}%)")
    print(f"Average response time: {avg_response_time:.2f}s")
    print(f"Total test time: {total_time:.2f}s")
    print()

    print("Intent Distribution:")
    for intent, count in sorted(intent_stats.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / successful) * 100
        print(f"  {intent}: {count} ({percentage:.1f}%)")
    print()

    print("Tool Usage:")
    for tool, count in sorted(tool_stats.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / successful) * 100
        print(f"  {tool}: {count} ({percentage:.1f}%)")
    print()

    # Response time statistics
    response_times = [r["response_time"] for r in results if r["success"]]
    if response_times:
        print("Response Time Statistics:")
        print(f"  Min: {min(response_times):.2f}s")
        print(f"  Max: {max(response_times):.2f}s")
        print(f"  Avg: {sum(response_times)/len(response_times):.2f}s")
        print()

    # Show sample failures
    failures = [r for r in results if not r["success"]]
    if failures:
        print("Sample Failures (first 10):")
        for failure in failures[:10]:
            print(f"  [{failure['index']}] {failure['question']}")
            print(f"      Error: {failure['error']}")
        print()

    # Save detailed results
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    results_file = f"test_results_1000_{timestamp}.json"

    with open(results_file, 'w') as f:
        json.dump({
            "summary": {
                "total": len(TEST_QUERIES),
                "successful": successful,
                "failed": failed,
                "success_rate": success_rate,
                "avg_response_time": avg_response_time,
                "total_time": total_time
            },
            "intent_stats": intent_stats,
            "tool_stats": tool_stats,
            "results": results
        }, f, indent=2)

    print(f"Detailed results saved to: {results_file}")
    print("=" * 80)

    # Final grade
    if success_rate >= 95:
        grade = "A+"
    elif success_rate >= 90:
        grade = "A"
    elif success_rate >= 85:
        grade = "B+"
    elif success_rate >= 80:
        grade = "B"
    elif success_rate >= 75:
        grade = "C+"
    elif success_rate >= 70:
        grade = "C"
    else:
        grade = "F"

    print()
    print(f"FINAL GRADE: {grade}")
    print(f"Success Rate: {success_rate:.1f}%")
    print(f"Average Response Time: {avg_response_time:.2f}s")
    print()
    print("=" * 80)

if __name__ == "__main__":
    run_tests()
